version: '2'
services:
    cidades-app:
        image: cidades
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cidades-mysql:3306/cidades?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cidades-mysql:
        extends:
            file: mysql.yml
            service: cidades-mysql
